/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.hal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hal.hal.Action#getActuator <em>Actuator</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.Action#getCommand <em>Command</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hal.hal.HalPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Actuator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actuator</em>' reference.
   * @see #setActuator(Device)
   * @see org.xtext.example.hal.hal.HalPackage#getAction_Actuator()
   * @model
   * @generated
   */
  Device getActuator();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.Action#getActuator <em>Actuator</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actuator</em>' reference.
   * @see #getActuator()
   * @generated
   */
  void setActuator(Device value);

  /**
   * Returns the value of the '<em><b>Command</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' reference.
   * @see #setCommand(Command)
   * @see org.xtext.example.hal.hal.HalPackage#getAction_Command()
   * @model
   * @generated
   */
  Command getCommand();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.Action#getCommand <em>Command</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' reference.
   * @see #getCommand()
   * @generated
   */
  void setCommand(Command value);

} // Action
