/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.hal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actuator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hal.hal.Actuator#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hal.hal.HalPackage#getActuator()
 * @model
 * @generated
 */
public interface Actuator extends DeviceType
{
  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hal.hal.Command}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference list.
   * @see org.xtext.example.hal.hal.HalPackage#getActuator_Commands()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommands();

} // Actuator
