/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.hal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Device</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hal.hal.Device#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.Device#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.Device#getLengthPos <em>Length Pos</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.Device#getWidthPos <em>Width Pos</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hal.hal.HalPackage#getDevice()
 * @model
 * @generated
 */
public interface Device extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.hal.hal.HalPackage#getDevice_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.Device#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(DeviceType)
   * @see org.xtext.example.hal.hal.HalPackage#getDevice_Type()
   * @model
   * @generated
   */
  DeviceType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.Device#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(DeviceType value);

  /**
   * Returns the value of the '<em><b>Length Pos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length Pos</em>' attribute.
   * @see #setLengthPos(float)
   * @see org.xtext.example.hal.hal.HalPackage#getDevice_LengthPos()
   * @model
   * @generated
   */
  float getLengthPos();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.Device#getLengthPos <em>Length Pos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length Pos</em>' attribute.
   * @see #getLengthPos()
   * @generated
   */
  void setLengthPos(float value);

  /**
   * Returns the value of the '<em><b>Width Pos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width Pos</em>' attribute.
   * @see #setWidthPos(float)
   * @see org.xtext.example.hal.hal.HalPackage#getDevice_WidthPos()
   * @model
   * @generated
   */
  float getWidthPos();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.Device#getWidthPos <em>Width Pos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width Pos</em>' attribute.
   * @see #getWidthPos()
   * @generated
   */
  void setWidthPos(float value);

} // Device
