/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.hal;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.hal.hal.HalFactory
 * @model kind="package"
 * @generated
 */
public interface HalPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hal";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/hal/HAL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hal";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HalPackage eINSTANCE = org.xtext.example.hal.hal.impl.HalPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.HALImpl <em>HAL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.HALImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getHAL()
   * @generated
   */
  int HAL = 0;

  /**
   * The feature id for the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAL__PASSWORD = 0;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAL__ADDRESS = 1;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAL__TYPES = 2;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAL__ROOMS = 3;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAL__RULES = 4;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAL__ENTRIES = 5;

  /**
   * The number of structural features of the '<em>HAL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAL_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.DeviceTypeImpl <em>Device Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.DeviceTypeImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getDeviceType()
   * @generated
   */
  int DEVICE_TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Device Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.BooleanExpressionImpl <em>Boolean Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.BooleanExpressionImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getBooleanExpression()
   * @generated
   */
  int BOOLEAN_EXPRESSION = 2;

  /**
   * The feature id for the '<em><b>Negated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION__NEGATED = 0;

  /**
   * The number of structural features of the '<em>Boolean Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.RoomImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__LENGTH = 1;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__WIDTH = 2;

  /**
   * The feature id for the '<em><b>Devices</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__DEVICES = 3;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.AutomationRuleImpl <em>Automation Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.AutomationRuleImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getAutomationRule()
   * @generated
   */
  int AUTOMATION_RULE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATION_RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Active</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATION_RULE__ACTIVE = 1;

  /**
   * The feature id for the '<em><b>Precondition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATION_RULE__PRECONDITION = 2;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATION_RULE__ACTIONS = 3;

  /**
   * The number of structural features of the '<em>Automation Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATION_RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.SensorEntryImpl <em>Sensor Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.SensorEntryImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getSensorEntry()
   * @generated
   */
  int SENSOR_ENTRY = 5;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_ENTRY__SENSOR = 0;

  /**
   * The feature id for the '<em><b>Reading</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_ENTRY__READING = 1;

  /**
   * The feature id for the '<em><b>Time Stamp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_ENTRY__TIME_STAMP = 2;

  /**
   * The number of structural features of the '<em>Sensor Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_ENTRY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.DeviceImpl <em>Device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.DeviceImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getDevice()
   * @generated
   */
  int DEVICE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Length Pos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__LENGTH_POS = 2;

  /**
   * The feature id for the '<em><b>Width Pos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__WIDTH_POS = 3;

  /**
   * The number of structural features of the '<em>Device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.ActionImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getAction()
   * @generated
   */
  int ACTION = 7;

  /**
   * The feature id for the '<em><b>Actuator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ACTUATOR = 0;

  /**
   * The feature id for the '<em><b>Command</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__COMMAND = 1;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.AtomicRelationalTermImpl <em>Atomic Relational Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.AtomicRelationalTermImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getAtomicRelationalTerm()
   * @generated
   */
  int ATOMIC_RELATIONAL_TERM = 8;

  /**
   * The feature id for the '<em><b>Negated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_RELATIONAL_TERM__NEGATED = BOOLEAN_EXPRESSION__NEGATED;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_RELATIONAL_TERM__SENSOR = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_RELATIONAL_TERM__OPERATOR = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Compared Against Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_RELATIONAL_TERM__COMPARED_AGAINST_VALUE = BOOLEAN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Atomic Relational Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_RELATIONAL_TERM_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.CompoundRelationalTermImpl <em>Compound Relational Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.CompoundRelationalTermImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getCompoundRelationalTerm()
   * @generated
   */
  int COMPOUND_RELATIONAL_TERM = 9;

  /**
   * The feature id for the '<em><b>Negated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_RELATIONAL_TERM__NEGATED = BOOLEAN_EXPRESSION__NEGATED;

  /**
   * The feature id for the '<em><b>LHS</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_RELATIONAL_TERM__LHS = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_RELATIONAL_TERM__OPERATOR = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>RHS</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_RELATIONAL_TERM__RHS = BOOLEAN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Compound Relational Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_RELATIONAL_TERM_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.CommandImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__NAME = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.SensorImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = DEVICE_TYPE__NAME;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = DEVICE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.impl.ActuatorImpl <em>Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.impl.ActuatorImpl
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getActuator()
   * @generated
   */
  int ACTUATOR = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__NAME = DEVICE_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__COMMANDS = DEVICE_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_FEATURE_COUNT = DEVICE_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.ComparisonOperator <em>Comparison Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.ComparisonOperator
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getComparisonOperator()
   * @generated
   */
  int COMPARISON_OPERATOR = 13;

  /**
   * The meta object id for the '{@link org.xtext.example.hal.hal.BooleanOperator <em>Boolean Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hal.hal.BooleanOperator
   * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getBooleanOperator()
   * @generated
   */
  int BOOLEAN_OPERATOR = 14;


  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.HAL <em>HAL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>HAL</em>'.
   * @see org.xtext.example.hal.hal.HAL
   * @generated
   */
  EClass getHAL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.HAL#getPassword <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Password</em>'.
   * @see org.xtext.example.hal.hal.HAL#getPassword()
   * @see #getHAL()
   * @generated
   */
  EAttribute getHAL_Password();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.HAL#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.xtext.example.hal.hal.HAL#getAddress()
   * @see #getHAL()
   * @generated
   */
  EAttribute getHAL_Address();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hal.hal.HAL#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see org.xtext.example.hal.hal.HAL#getTypes()
   * @see #getHAL()
   * @generated
   */
  EReference getHAL_Types();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hal.hal.HAL#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see org.xtext.example.hal.hal.HAL#getRooms()
   * @see #getHAL()
   * @generated
   */
  EReference getHAL_Rooms();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hal.hal.HAL#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see org.xtext.example.hal.hal.HAL#getRules()
   * @see #getHAL()
   * @generated
   */
  EReference getHAL_Rules();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hal.hal.HAL#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.xtext.example.hal.hal.HAL#getEntries()
   * @see #getHAL()
   * @generated
   */
  EReference getHAL_Entries();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.DeviceType <em>Device Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device Type</em>'.
   * @see org.xtext.example.hal.hal.DeviceType
   * @generated
   */
  EClass getDeviceType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.DeviceType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hal.hal.DeviceType#getName()
   * @see #getDeviceType()
   * @generated
   */
  EAttribute getDeviceType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.BooleanExpression <em>Boolean Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Expression</em>'.
   * @see org.xtext.example.hal.hal.BooleanExpression
   * @generated
   */
  EClass getBooleanExpression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.BooleanExpression#isNegated <em>Negated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Negated</em>'.
   * @see org.xtext.example.hal.hal.BooleanExpression#isNegated()
   * @see #getBooleanExpression()
   * @generated
   */
  EAttribute getBooleanExpression_Negated();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.xtext.example.hal.hal.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hal.hal.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.Room#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.xtext.example.hal.hal.Room#getLength()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Length();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.Room#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.xtext.example.hal.hal.Room#getWidth()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Width();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hal.hal.Room#getDevices <em>Devices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Devices</em>'.
   * @see org.xtext.example.hal.hal.Room#getDevices()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Devices();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.AutomationRule <em>Automation Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Automation Rule</em>'.
   * @see org.xtext.example.hal.hal.AutomationRule
   * @generated
   */
  EClass getAutomationRule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.AutomationRule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hal.hal.AutomationRule#getName()
   * @see #getAutomationRule()
   * @generated
   */
  EAttribute getAutomationRule_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.AutomationRule#isActive <em>Active</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Active</em>'.
   * @see org.xtext.example.hal.hal.AutomationRule#isActive()
   * @see #getAutomationRule()
   * @generated
   */
  EAttribute getAutomationRule_Active();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hal.hal.AutomationRule#getPrecondition <em>Precondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Precondition</em>'.
   * @see org.xtext.example.hal.hal.AutomationRule#getPrecondition()
   * @see #getAutomationRule()
   * @generated
   */
  EReference getAutomationRule_Precondition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hal.hal.AutomationRule#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.hal.hal.AutomationRule#getActions()
   * @see #getAutomationRule()
   * @generated
   */
  EReference getAutomationRule_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.SensorEntry <em>Sensor Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Entry</em>'.
   * @see org.xtext.example.hal.hal.SensorEntry
   * @generated
   */
  EClass getSensorEntry();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hal.hal.SensorEntry#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor</em>'.
   * @see org.xtext.example.hal.hal.SensorEntry#getSensor()
   * @see #getSensorEntry()
   * @generated
   */
  EReference getSensorEntry_Sensor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.SensorEntry#getReading <em>Reading</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reading</em>'.
   * @see org.xtext.example.hal.hal.SensorEntry#getReading()
   * @see #getSensorEntry()
   * @generated
   */
  EAttribute getSensorEntry_Reading();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.SensorEntry#getTimeStamp <em>Time Stamp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time Stamp</em>'.
   * @see org.xtext.example.hal.hal.SensorEntry#getTimeStamp()
   * @see #getSensorEntry()
   * @generated
   */
  EAttribute getSensorEntry_TimeStamp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.Device <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device</em>'.
   * @see org.xtext.example.hal.hal.Device
   * @generated
   */
  EClass getDevice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.Device#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hal.hal.Device#getName()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hal.hal.Device#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.example.hal.hal.Device#getType()
   * @see #getDevice()
   * @generated
   */
  EReference getDevice_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.Device#getLengthPos <em>Length Pos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length Pos</em>'.
   * @see org.xtext.example.hal.hal.Device#getLengthPos()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_LengthPos();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.Device#getWidthPos <em>Width Pos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width Pos</em>'.
   * @see org.xtext.example.hal.hal.Device#getWidthPos()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_WidthPos();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.hal.hal.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hal.hal.Action#getActuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Actuator</em>'.
   * @see org.xtext.example.hal.hal.Action#getActuator()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Actuator();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hal.hal.Action#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Command</em>'.
   * @see org.xtext.example.hal.hal.Action#getCommand()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Command();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.AtomicRelationalTerm <em>Atomic Relational Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atomic Relational Term</em>'.
   * @see org.xtext.example.hal.hal.AtomicRelationalTerm
   * @generated
   */
  EClass getAtomicRelationalTerm();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hal.hal.AtomicRelationalTerm#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor</em>'.
   * @see org.xtext.example.hal.hal.AtomicRelationalTerm#getSensor()
   * @see #getAtomicRelationalTerm()
   * @generated
   */
  EReference getAtomicRelationalTerm_Sensor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.AtomicRelationalTerm#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see org.xtext.example.hal.hal.AtomicRelationalTerm#getOperator()
   * @see #getAtomicRelationalTerm()
   * @generated
   */
  EAttribute getAtomicRelationalTerm_Operator();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.AtomicRelationalTerm#getComparedAgainstValue <em>Compared Against Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Compared Against Value</em>'.
   * @see org.xtext.example.hal.hal.AtomicRelationalTerm#getComparedAgainstValue()
   * @see #getAtomicRelationalTerm()
   * @generated
   */
  EAttribute getAtomicRelationalTerm_ComparedAgainstValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.CompoundRelationalTerm <em>Compound Relational Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compound Relational Term</em>'.
   * @see org.xtext.example.hal.hal.CompoundRelationalTerm
   * @generated
   */
  EClass getCompoundRelationalTerm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hal.hal.CompoundRelationalTerm#getLHS <em>LHS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>LHS</em>'.
   * @see org.xtext.example.hal.hal.CompoundRelationalTerm#getLHS()
   * @see #getCompoundRelationalTerm()
   * @generated
   */
  EReference getCompoundRelationalTerm_LHS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.CompoundRelationalTerm#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see org.xtext.example.hal.hal.CompoundRelationalTerm#getOperator()
   * @see #getCompoundRelationalTerm()
   * @generated
   */
  EAttribute getCompoundRelationalTerm_Operator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hal.hal.CompoundRelationalTerm#getRHS <em>RHS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>RHS</em>'.
   * @see org.xtext.example.hal.hal.CompoundRelationalTerm#getRHS()
   * @see #getCompoundRelationalTerm()
   * @generated
   */
  EReference getCompoundRelationalTerm_RHS();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.example.hal.hal.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hal.hal.Command#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hal.hal.Command#getName()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see org.xtext.example.hal.hal.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hal.hal.Actuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator</em>'.
   * @see org.xtext.example.hal.hal.Actuator
   * @generated
   */
  EClass getActuator();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hal.hal.Actuator#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.example.hal.hal.Actuator#getCommands()
   * @see #getActuator()
   * @generated
   */
  EReference getActuator_Commands();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.hal.hal.ComparisonOperator <em>Comparison Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comparison Operator</em>'.
   * @see org.xtext.example.hal.hal.ComparisonOperator
   * @generated
   */
  EEnum getComparisonOperator();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.hal.hal.BooleanOperator <em>Boolean Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Boolean Operator</em>'.
   * @see org.xtext.example.hal.hal.BooleanOperator
   * @generated
   */
  EEnum getBooleanOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HalFactory getHalFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.HALImpl <em>HAL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.HALImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getHAL()
     * @generated
     */
    EClass HAL = eINSTANCE.getHAL();

    /**
     * The meta object literal for the '<em><b>Password</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HAL__PASSWORD = eINSTANCE.getHAL_Password();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HAL__ADDRESS = eINSTANCE.getHAL_Address();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HAL__TYPES = eINSTANCE.getHAL_Types();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HAL__ROOMS = eINSTANCE.getHAL_Rooms();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HAL__RULES = eINSTANCE.getHAL_Rules();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HAL__ENTRIES = eINSTANCE.getHAL_Entries();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.DeviceTypeImpl <em>Device Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.DeviceTypeImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getDeviceType()
     * @generated
     */
    EClass DEVICE_TYPE = eINSTANCE.getDeviceType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE_TYPE__NAME = eINSTANCE.getDeviceType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.BooleanExpressionImpl <em>Boolean Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.BooleanExpressionImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getBooleanExpression()
     * @generated
     */
    EClass BOOLEAN_EXPRESSION = eINSTANCE.getBooleanExpression();

    /**
     * The meta object literal for the '<em><b>Negated</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_EXPRESSION__NEGATED = eINSTANCE.getBooleanExpression_Negated();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.RoomImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__LENGTH = eINSTANCE.getRoom_Length();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__WIDTH = eINSTANCE.getRoom_Width();

    /**
     * The meta object literal for the '<em><b>Devices</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__DEVICES = eINSTANCE.getRoom_Devices();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.AutomationRuleImpl <em>Automation Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.AutomationRuleImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getAutomationRule()
     * @generated
     */
    EClass AUTOMATION_RULE = eINSTANCE.getAutomationRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTOMATION_RULE__NAME = eINSTANCE.getAutomationRule_Name();

    /**
     * The meta object literal for the '<em><b>Active</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTOMATION_RULE__ACTIVE = eINSTANCE.getAutomationRule_Active();

    /**
     * The meta object literal for the '<em><b>Precondition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTOMATION_RULE__PRECONDITION = eINSTANCE.getAutomationRule_Precondition();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTOMATION_RULE__ACTIONS = eINSTANCE.getAutomationRule_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.SensorEntryImpl <em>Sensor Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.SensorEntryImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getSensorEntry()
     * @generated
     */
    EClass SENSOR_ENTRY = eINSTANCE.getSensorEntry();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_ENTRY__SENSOR = eINSTANCE.getSensorEntry_Sensor();

    /**
     * The meta object literal for the '<em><b>Reading</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_ENTRY__READING = eINSTANCE.getSensorEntry_Reading();

    /**
     * The meta object literal for the '<em><b>Time Stamp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_ENTRY__TIME_STAMP = eINSTANCE.getSensorEntry_TimeStamp();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.DeviceImpl <em>Device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.DeviceImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getDevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getDevice();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__NAME = eINSTANCE.getDevice_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE__TYPE = eINSTANCE.getDevice_Type();

    /**
     * The meta object literal for the '<em><b>Length Pos</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__LENGTH_POS = eINSTANCE.getDevice_LengthPos();

    /**
     * The meta object literal for the '<em><b>Width Pos</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__WIDTH_POS = eINSTANCE.getDevice_WidthPos();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.ActionImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Actuator</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ACTUATOR = eINSTANCE.getAction_Actuator();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__COMMAND = eINSTANCE.getAction_Command();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.AtomicRelationalTermImpl <em>Atomic Relational Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.AtomicRelationalTermImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getAtomicRelationalTerm()
     * @generated
     */
    EClass ATOMIC_RELATIONAL_TERM = eINSTANCE.getAtomicRelationalTerm();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATOMIC_RELATIONAL_TERM__SENSOR = eINSTANCE.getAtomicRelationalTerm_Sensor();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_RELATIONAL_TERM__OPERATOR = eINSTANCE.getAtomicRelationalTerm_Operator();

    /**
     * The meta object literal for the '<em><b>Compared Against Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_RELATIONAL_TERM__COMPARED_AGAINST_VALUE = eINSTANCE.getAtomicRelationalTerm_ComparedAgainstValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.CompoundRelationalTermImpl <em>Compound Relational Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.CompoundRelationalTermImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getCompoundRelationalTerm()
     * @generated
     */
    EClass COMPOUND_RELATIONAL_TERM = eINSTANCE.getCompoundRelationalTerm();

    /**
     * The meta object literal for the '<em><b>LHS</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOUND_RELATIONAL_TERM__LHS = eINSTANCE.getCompoundRelationalTerm_LHS();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOUND_RELATIONAL_TERM__OPERATOR = eINSTANCE.getCompoundRelationalTerm_Operator();

    /**
     * The meta object literal for the '<em><b>RHS</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOUND_RELATIONAL_TERM__RHS = eINSTANCE.getCompoundRelationalTerm_RHS();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.CommandImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__NAME = eINSTANCE.getCommand_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.SensorImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.impl.ActuatorImpl <em>Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.impl.ActuatorImpl
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getActuator()
     * @generated
     */
    EClass ACTUATOR = eINSTANCE.getActuator();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR__COMMANDS = eINSTANCE.getActuator_Commands();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.ComparisonOperator <em>Comparison Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.ComparisonOperator
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getComparisonOperator()
     * @generated
     */
    EEnum COMPARISON_OPERATOR = eINSTANCE.getComparisonOperator();

    /**
     * The meta object literal for the '{@link org.xtext.example.hal.hal.BooleanOperator <em>Boolean Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hal.hal.BooleanOperator
     * @see org.xtext.example.hal.hal.impl.HalPackageImpl#getBooleanOperator()
     * @generated
     */
    EEnum BOOLEAN_OPERATOR = eINSTANCE.getBooleanOperator();

  }

} //HalPackage
