/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.hal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.hal.hal.HalPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends DeviceType
{
} // Sensor
