/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.hal.HalRuntimeModule;
import org.xtext.example.hal.HalStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HalIdeSetup extends HalStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HalRuntimeModule(), new HalIdeModule()));
	}
	
}
