/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.hal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hal.hal.SensorEntry#getSensor <em>Sensor</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.SensorEntry#getReading <em>Reading</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.SensorEntry#getTimeStamp <em>Time Stamp</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hal.hal.HalPackage#getSensorEntry()
 * @model
 * @generated
 */
public interface SensorEntry extends EObject
{
  /**
   * Returns the value of the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor</em>' reference.
   * @see #setSensor(Device)
   * @see org.xtext.example.hal.hal.HalPackage#getSensorEntry_Sensor()
   * @model
   * @generated
   */
  Device getSensor();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.SensorEntry#getSensor <em>Sensor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensor</em>' reference.
   * @see #getSensor()
   * @generated
   */
  void setSensor(Device value);

  /**
   * Returns the value of the '<em><b>Reading</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reading</em>' attribute.
   * @see #setReading(String)
   * @see org.xtext.example.hal.hal.HalPackage#getSensorEntry_Reading()
   * @model
   * @generated
   */
  String getReading();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.SensorEntry#getReading <em>Reading</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reading</em>' attribute.
   * @see #getReading()
   * @generated
   */
  void setReading(String value);

  /**
   * Returns the value of the '<em><b>Time Stamp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Stamp</em>' attribute.
   * @see #setTimeStamp(long)
   * @see org.xtext.example.hal.hal.HalPackage#getSensorEntry_TimeStamp()
   * @model
   * @generated
   */
  long getTimeStamp();

  /**
   * Sets the value of the '{@link org.xtext.example.hal.hal.SensorEntry#getTimeStamp <em>Time Stamp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Stamp</em>' attribute.
   * @see #getTimeStamp()
   * @generated
   */
  void setTimeStamp(long value);

} // SensorEntry
