/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HalUiModule extends AbstractHalUiModule {

	public HalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
