/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HalStandaloneSetup extends HalStandaloneSetupGenerated {

	public static void doSetup() {
		new HalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
