/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.hal.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.hal.hal.Device;
import org.xtext.example.hal.hal.DeviceType;
import org.xtext.example.hal.hal.HalPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Device</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hal.hal.impl.DeviceImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.impl.DeviceImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.impl.DeviceImpl#getLengthPos <em>Length Pos</em>}</li>
 *   <li>{@link org.xtext.example.hal.hal.impl.DeviceImpl#getWidthPos <em>Width Pos</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeviceImpl extends MinimalEObjectImpl.Container implements Device
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected DeviceType type;

  /**
   * The default value of the '{@link #getLengthPos() <em>Length Pos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLengthPos()
   * @generated
   * @ordered
   */
  protected static final float LENGTH_POS_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getLengthPos() <em>Length Pos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLengthPos()
   * @generated
   * @ordered
   */
  protected float lengthPos = LENGTH_POS_EDEFAULT;

  /**
   * The default value of the '{@link #getWidthPos() <em>Width Pos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidthPos()
   * @generated
   * @ordered
   */
  protected static final float WIDTH_POS_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getWidthPos() <em>Width Pos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidthPos()
   * @generated
   * @ordered
   */
  protected float widthPos = WIDTH_POS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeviceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HalPackage.Literals.DEVICE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HalPackage.DEVICE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeviceType getType()
  {
    if (type != null && type.eIsProxy())
    {
      InternalEObject oldType = (InternalEObject)type;
      type = (DeviceType)eResolveProxy(oldType);
      if (type != oldType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, HalPackage.DEVICE__TYPE, oldType, type));
      }
    }
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DeviceType basicGetType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(DeviceType newType)
  {
    DeviceType oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HalPackage.DEVICE__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public float getLengthPos()
  {
    return lengthPos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLengthPos(float newLengthPos)
  {
    float oldLengthPos = lengthPos;
    lengthPos = newLengthPos;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HalPackage.DEVICE__LENGTH_POS, oldLengthPos, lengthPos));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public float getWidthPos()
  {
    return widthPos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWidthPos(float newWidthPos)
  {
    float oldWidthPos = widthPos;
    widthPos = newWidthPos;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HalPackage.DEVICE__WIDTH_POS, oldWidthPos, widthPos));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HalPackage.DEVICE__NAME:
        return getName();
      case HalPackage.DEVICE__TYPE:
        if (resolve) return getType();
        return basicGetType();
      case HalPackage.DEVICE__LENGTH_POS:
        return getLengthPos();
      case HalPackage.DEVICE__WIDTH_POS:
        return getWidthPos();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HalPackage.DEVICE__NAME:
        setName((String)newValue);
        return;
      case HalPackage.DEVICE__TYPE:
        setType((DeviceType)newValue);
        return;
      case HalPackage.DEVICE__LENGTH_POS:
        setLengthPos((Float)newValue);
        return;
      case HalPackage.DEVICE__WIDTH_POS:
        setWidthPos((Float)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HalPackage.DEVICE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case HalPackage.DEVICE__TYPE:
        setType((DeviceType)null);
        return;
      case HalPackage.DEVICE__LENGTH_POS:
        setLengthPos(LENGTH_POS_EDEFAULT);
        return;
      case HalPackage.DEVICE__WIDTH_POS:
        setWidthPos(WIDTH_POS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HalPackage.DEVICE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case HalPackage.DEVICE__TYPE:
        return type != null;
      case HalPackage.DEVICE__LENGTH_POS:
        return lengthPos != LENGTH_POS_EDEFAULT;
      case HalPackage.DEVICE__WIDTH_POS:
        return widthPos != WIDTH_POS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", lengthPos: ");
    result.append(lengthPos);
    result.append(", widthPos: ");
    result.append(widthPos);
    result.append(')');
    return result.toString();
  }

} //DeviceImpl
