/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.hal.ui.internal.HalActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(HalActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		HalActivator activator = HalActivator.getInstance();
		return activator != null ? activator.getInjector(HalActivator.ORG_XTEXT_EXAMPLE_HAL_HAL) : null;
	}

}
