/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.hal.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class HalProposalProvider extends AbstractHalProposalProvider {
}
